### ISSUE TITLE
Standalone dashboard feature

### ISSUE THREAD

**Issue by ImoutoChan** [filipbekic01/resqueue#10]
Hello, great project!

I would like to suggest an option to run this dashboard as a standalone application. I imagine creating a Docker image that can be run independently and access a shared SQL transport database. The reason is that, in most cases, there are multiple services, and it’s not always clear where this dashboard should be hosted. Running the dashboard within each service seems redundant to me.

**Comment by filipbekic01** [comment]
> Hello, great project!
> 
> I would like to suggest an option to run this dashboard as a standalone application. I imagine creating a Docker image that can be run independently and access a shared SQL transport database. The reason is that, in most cases, there are multiple services, and it’s not always clear where this dashboard should be hosted. Running the dashboard within each service seems redundant to me.

The dashboard doesn’t need to be part of every running service. You can create a lightweight service (around 10 lines) with just the ResQueue and MassTransit dependencies. Simply point it to your remote database, and it will serve the dashboard without impacting other services.

That said, I really appreciate your suggestion! We’ll definitely work on creating a Docker image so you can just pass a few environment variables and run it. I’ll see if I can get it working this week. Once I get docker image out, I'll close this issue.

**Comment by MagnusHJensen** [comment]
Wanted to chime in, a docker image sounds great for this type of project :)

**Comment by MagnusHJensen** [comment]
Adding a new comment here, is it possible to run this standalone in it's current state, without any masstransit dependency or setup? @filipbekic01

**Comment by filipbekic01** [comment]
@MagnusHJensen 

> Adding a new comment here, is it possible to run this standalone in it's current state, without any masstransit dependency or setup? @filipbekic01

Yes, as I state above, you can create simple console application, configure SqlTransportOptions and add/use ResQueue.

```C#
builder.Services.AddOptions<SqlTransportOptions>().Configure(options =>
{
    options.ConnectionString =
    "Host=localhost;Database=sandbox100;Username=postgres;Password=postgres;";
});

builer.Services.AddResQueue();

// ...

app.UseResQueue();
```

Technically ResQueue does have MassTransit reference but only because it reads SqlTransportOptions in it's source, it wont start MassTransit in background.

**Comment by filipbekic01** [comment]
Docker support added https://github.com/filipbekic01/ResQueue?tab=readme-ov-file#docker-optional

Thanks to @miroljub1995
